disabled_rules:
  - empty_count
  - force_cast
  - force_unwrapping
  - function_parameter_count
  - nesting
  - private_over_fileprivate
  - sorted_imports
  - todo
  - trailing_whitespace

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

excluded:
  - Pods
  - QuakeTower/R.generated.swift

line_length: 120

type_body_length:
  - 300 # warning
  - 400 # error

function_body_length:
  - 100 # warning
  - 300 # error

file_length:
  warning: 500
  error: 1200

identifier_name:
  allowed_symbols: "_"
  min_length:
    error: 4
  excluded:
    - i
    - j
    - k
    - r
    - g
    - b
    - id
    - by
    - vc
    - url
    - URL
    - uri
    - key
    - log
    - db
    - top
    - btm
    - now
    - row
    - tab
    - app
    - bio
    - me
    - GET
    - PUT
    - max
    - min
    - end
    - rgb
    - tag
    - hex
    - to
    - day
    - api
    - all
    - uns
    - idx